### ISSUE TITLE
Cant add plugin to current version

### ISSUE THREAD

**Issue by maeno14** [melohagan/budibase-datasource-supabase#2] opened 2022-09-24 13:05 UTC
When i try to add the plugin by the admin panel in the plugin section it gives error that schema.extra is not allowed, not sure if i am doing something wrong here, tried googling but didnt find answer.
![imagen](https://user-images.githubusercontent.com/62074708/192099511-5ceb039c-f46f-4c86-b352-3daa6bee9aa1.png)
![imagen](https://user-images.githubusercontent.com/62074708/192099513-1514f09d-796f-457e-9f21-0587fe6d966e.png)

My version is:
![imagen](https://user-images.githubusercontent.com/62074708/192099514-cb602f39-c4b1-4bee-be40-5d6f799c067f.png)

**Comment by melohagan** [comment] 2022-09-26 07:02
Duplicate of: https://github.com/melohagan/budibase-datasource-supabase/issues/1

**Closed as completed by melohagan** 2022-09-26 07:02 UTC
